apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site-container
          image: gcr.io/personal-website-421100/personal-site:bc048038d24b
          ports:
            - containerPort: 8080
          env:
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_PASSWORD
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-username
                  key: EMAIL_USERNAME


