apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
      annotations:
        rollme: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: site-container
          image: a26blass/personal-site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_PASSWORD
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-username
                  key: EMAIL_USERNAME

