apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp-container
          image: gcr.io/personal-website-421100/personal-site:bc048038d24b
          ports:
            - containerPort: 8080

