apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  selector:
    app: site
  ports:
    - name: "http-endpoint"
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort 
