apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-ingress
  namespace: default
  annotations:
    cert-manager.io/issuer: "cert-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - alexblass.me
    secretName: cert-prod-tls
  rules:
    - host: alexblass.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testapp-service
                port:
                  number: 80

