apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ablass@andrew.cmu.edu 
    privateKeySecretRef:
      name: cert-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx