# This issuer is for STAGING ONLY - DO NOT USE IN PROD ENVIRONMENT
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ablass@andrew.cmu.edu
    privateKeySecretRef:
      name: cert-staging
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx