name: cicd

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: personal-site
  DOCKER_TAG: ${{ github.sha }}

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get changed site files
        id: changed-site-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            app.js
            routes/**
            views/**
            public/**
            Dockerfile

      - name: Get changed helm files
        id: changed-infra-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            helm/**

    outputs:
      site-changed: ${{ steps.changed-site-files.outputs.any_changed }}
      infra-changed: ${{ steps.changed-infra-files.outputs.any_changed }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-changed-files
    if: needs.check-changed-files.outputs.site-changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image (by commit and latest)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

